name: flutterXO
description: "\"torikkusu\"is a simple yet exciting strategic game. The game requires two players, each drawing either a circle or a cross in the squares of a 3x3 grid. The goal of the game is to have three of your symbol in a row, whether it be vertically, horizontally, or diagonally, before your opponent. This game requires strategic planning and quick thinking. It’s fun and engaging, and can be played anytime, anywhere! 😊"

publish_to: 'none'


version: 1.0.1+1

environment:
  sdk: 3.8.1


dependencies:

dev_dependencies:
  flutter_test:
    sdk: flutter.
  flutter_lints: ^3.0.0



flutter:
  uses-material-design: true

  #assets:
  #   - images/a_dot_ham.jpeg

  fonts:
    #  - family: Overlock
    #    fonts:
    #     - asset: assets/Font/Overlock-Regular.ttf
    #  - family: YujiSyuku
    #    fonts:
    #      - asset: assets/Font/YujiSyuku-Regular.ttf